//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Persona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar_Persona();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Persona", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Listar_PersonaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Crear_Persona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Crear_Persona(string ci, string nombre, string fecha_nac, string telefono, string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Crear_Persona", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Crear_PersonaAsync(string ci, string nombre, string fecha_nac, string telefono, string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar_Persona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Actualizar_Persona(string ci, string nombre, string fecha_nac, string telefono, string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar_Persona", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Actualizar_PersonaAsync(string ci, string nombre, string fecha_nac, string telefono, string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar_Persona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Eliminar_Persona(string ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar_Persona", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Eliminar_PersonaAsync(string ci);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WindowsFormsApplication1.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.WebServiceSoap>, WindowsFormsApplication1.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar_Persona() {
            return base.Channel.Listar_Persona();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Listar_PersonaAsync() {
            return base.Channel.Listar_PersonaAsync();
        }
        
        public bool Crear_Persona(string ci, string nombre, string fecha_nac, string telefono, string departamento) {
            return base.Channel.Crear_Persona(ci, nombre, fecha_nac, telefono, departamento);
        }
        
        public System.Threading.Tasks.Task<bool> Crear_PersonaAsync(string ci, string nombre, string fecha_nac, string telefono, string departamento) {
            return base.Channel.Crear_PersonaAsync(ci, nombre, fecha_nac, telefono, departamento);
        }
        
        public bool Actualizar_Persona(string ci, string nombre, string fecha_nac, string telefono, string departamento) {
            return base.Channel.Actualizar_Persona(ci, nombre, fecha_nac, telefono, departamento);
        }
        
        public System.Threading.Tasks.Task<bool> Actualizar_PersonaAsync(string ci, string nombre, string fecha_nac, string telefono, string departamento) {
            return base.Channel.Actualizar_PersonaAsync(ci, nombre, fecha_nac, telefono, departamento);
        }
        
        public bool Eliminar_Persona(string ci) {
            return base.Channel.Eliminar_Persona(ci);
        }
        
        public System.Threading.Tasks.Task<bool> Eliminar_PersonaAsync(string ci) {
            return base.Channel.Eliminar_PersonaAsync(ci);
        }
    }
}
